# Generated by Django 3.2.23 on 2024-01-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(upload_to='C:/Users/Admin/Desktop/Desk files/Akash_Work/Django/product/')),
                ('description', models.TextField()),
                ('code', models.CharField(max_length=100)),
                ('time_placed', models.TimeField(auto_now_add=True)),
                ('available_quantity', models.PositiveIntegerField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
